channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=25.2
- pip:
  - mlflow==2.18.0
  - cloudpickle==1.6.0
  - numpy==2.2.6
  - pandas==2.3.3
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.15.3
name: mlflow-env
